name: artexplorer
description: "An art exploration app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  google_sign_in: ^7.2.0
  bloc: ^9.2.1
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true

  assets:
    -  assets/icon/
    -  assets/buttons/

flutter_launcher_icons:
  image_path: "assets/icon/art_explorer_icon.png"

  android: "launcher_icon"
  image_path_android: "assets/icon/art_explorer_icon.png"
  min_sdk_android: 21 

  ios: true
  image_path_ios: "assets/icon/art_explorer_icon.png"
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/icon/art_explorer_icon.png"
    background_color: "#F0EBE1"
    theme_color: "#8C6B4A"

flutter_native_splash:
  color: "#2C2520" 
  image: assets/icon/art_explorer_icon.png
  fullscreen: true              
  android_12:
    color: "#2C2520"
    image: assets/icon/art_explorer_splash.png
    icon_background_color: "#2C2520"
  